### ISSUE TITLE
Number of crimes not updated

### ISSUE THREAD

**Issue by LaLeonie** [fac-17/CGKO-Week3#33]
I noticed a tiny bug: After searching for a valid postcode, when I type in an invalid postcode the list of crimes disappears but the number of crimes stays visible. See image below

<img width="642" alt="Screenshot 2019-07-19 at 10 31 53" src="https://user-images.githubusercontent.com/45558475/61525502-7a537800-aa10-11e9-9201-fcad476a7dad.png">

**Comment by gminova** [comment]
fixed
