### ISSUE TITLE
Nice testing.

### ISSUE THREAD

**Issue by RohanSSS** [fac-17/CGKO-Week3#40]
pretty good test coverage for the project

|File          |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
|--------------|----------|----------|----------|----------|-------------------|
|All files     |    98.75 |    66.67 |    93.75 |    98.68 |                   |
| functions.js |    96.67 |    66.67 |    83.33 |    96.15 |                 3 |
| tests.js     |      100 |      100 |      100 |      100 |                   |

good for keeping up with testing though, it's hard to keep on top of doing tests with such limited time.

**Comment by gminova** [comment]
Thank you!! :smile:
